/// Flutter icons Dashboard
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Dashboard
///      fonts:
///       - asset: fonts/Dashboard.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Dashboard {
  Dashboard._();

  static const _kFontFam = 'Dashboard';
  static const _kFontPkg = null;

  static const IconData final_icon = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
